  inputs: 
    solution_name:
      description: 'The name of the solution to worked on from Power Platform'
      required: true
      default: Examplesolution
    github_token:
      description: 'A valid Github token for create a pull request'

      #Once set to you prefered layout avoid changing these values
    unpacked_solution_path:
      description: 'The path to the unpacked solution'
      required: true
    solution_target_folder: 
      description: 'The name of the directory to be used or created when the solution is checked in *do not change*'
      required: true
      default: solutions/

  runs:
    using: "composite"
    steps:
    - name: Creating a branch for the ${{ inputs.solution_name }} solution
      uses: microsoft/powerplatform-actions/branch-solution@latest
      with:
        solution-folder: ${{ inputs.unpacked_solution_path}}
        solution-target-folder: ${{ inputs.solution_target_folder}}/${{ inputs.solution_name }}
        repo-token: ${{ inputs.github_token }}
        allow-empty-commit: true