  inputs: 
    solution_name:
      description: 'The name of the solution to worked on from Power Platform'
      required: true
      default: Examplesolution
    github_token:
      description: 'A valid Github token for create a pull request'

      #Once set to you prefered layout avoid changing these values
    solution_folder:
      description: 'The staging directory for the unpacked solution prior to check-in *do not change*'
      required: true
      default: out/solutions/
    solution_target_folder: 
      description: 'The name of the directory to be used or created when the solution is checked in *do not change*'
      required: true
      default: solutions/

  runs:
    using: "composite"
    steps:
    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@latest
      with:
        solution-folder: ${{ inputs.solution_folder}}/${{inputs.solution_name }}
        solution-target-folder: ${{ inputs.solution_target_folder}}/${{ inputs.solution_name }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true