name: Export, unpack solution, and create PR 

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'The solution name.'
        type: string
        default: Examplesolution     

env:
  SOLUTION_EXPORT_FOLDER: out/exported/


jobs:
  export-example-solution:
    runs-on: windows-latest
    environment: 
      name: development
      url: ${{vars.ENVIRONMENT_URL}}

    steps: 
    - name: Checkout
      uses: actions/checkout@v3.3.0
      with:
        lfs: true

    - name: Use variables
      run: |
        echo "solution_name input: ${{ inputs.solution_name }}"
        echo "SOLUTION_EXPORT_FOLDER environemnt variable: ${{ env.SOLUTION_EXPORT_FOLDER }}"
        echo "ENVIRONMENT_URL variable : ${{ vars.ENVIRONMENT_URL }}"
        echo "CLIENT_ID variable : ${{ vars.CLIENT_ID }}"
        echo "TENANT_ID variable : ${{ vars.TENANT_ID }}"

    - name: Exporting ${{ inputs.solution_name }} solution
      uses: microsoft/powerplatform-actions/export-solution@latest
      with:
        environment-url: ${{vars.ENVIRONMENT_URL}}
        app-id: ${{vars.CLIENT_ID}}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{vars.TENANT_ID}}
        solution-name: ${{ inputs.solution_name }}
        solution-output-file: ${{ env.SOLUTION_EXPORT_FOLDER }}/${{ inputs.solution_name }}.zip

    - name: Unpacking ${{ inputs.solution_name }} solution
      uses: paulbreuler/PowerPlatform-CLI-workflow-templates/componsite-actions/unpack-solution@main
      id: unpack_solution
      with:
        solution_name: ${{ inputs.solution_source_folder}}/${{ inputs.solution_name }}
        solution_export_folder: ${{ env.SOLUTION_EXPORT_FOLDER }}

    - name: Creating a branch with a new commit for the ${{ inputs.solution_name }} solution
      uses: paulbreuler/PowerPlatform-CLI-workflow-templates/componsite-actions/create-solution-branch@main
      with:
        unpacked_solution_path: ${{ steps.unpack_solution.outputs.unpacked_solution_path }}
        solution_target_folder: solutions/
        github_token: ${{ secrets.GH_PAT_TOKEN }}