name: Export, unpack solution, and create PR 

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'The solution name.'
        type: string
        default: Examplesolution     
      solution_exported_folder:
        description: 'The folder name for staging the exported solution *do not change*'
        required: true
        default: out/exported/

jobs:
  export-example-solution:
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: ${{vars.ENVIRONMENT_URL}}

    steps: 
    - name: Checkout
      uses: actions/checkout@v3.3.0
      with:
        lfs: true

    - name: Use variables
      run: |
        echo "solution_name input: ${{ inputs.solution_name }}"
        echo "solution_exported_folder input: ${{ inputs.solution_exported_folder }}"
        echo "ENVIRONMENT_URL variable : ${{ vars.ENVIRONMENT_URL }}"
        echo "CLIENT_ID variable : ${{ vars.CLIENT_ID }}"
        echo "TENANT_ID variable : ${{ vars.TENANT_ID }}"


    - name: export ${{ inputs.solution_name }} solution action
      uses: microsoft/powerplatform-actions/export-solution@latest
      with:
        environment-url: ${{vars.ENVIRONMENT_URL}}
        app-id: ${{vars.CLIENT_ID}}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        tenant-id: ${{vars.TENANT_ID}}
        solution-name: ${{ inputs.solution_name }}
        solution-output-file: ${{ inputs.solution_exported_folder}}/${{ inputs.solution_name }}.zip

    - name: unpack ${{ inputs.solution_name }} solution
      uses: paulbreuler/PowerPlatform-CLI-workflow-templates/componsite-actions/unpack-solution@main
      with:
        solution_name: ${{ inputs.solution_source_folder}}/${{ inputs.solution_name }}
        solution_exported_folder: ${{ inputs.solution_exported_folder}}