name: Export, unpack solution, and create PR 

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'The solution name.'
        type: string
        default: Examplesolution     

jobs:
  export-example-solution:
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: ${{env.ENVIRONMENT_URL}}

    steps: 
    
    - name: Checkout
      uses: actions/checkout@v3.3.0
    
    - name: export ${{ github.event.inputs.solution_name }} solution action
      uses: microsoft/powerplatform-actions/export-solution@latest
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{ github.event.inputs.solution_name }}
        solution-output-file: ${{ github.event.inputs.solution_exported_folder}}/${{ github.event.inputs.solution_name }}.zip

    - name: unpack ${{ github.event.inputs.solution_name }} solution
      uses: paulbreuler/PowerPlatform-CLI-workflow-templates/componsite-actions/unpack-solution.yml@main
      with:
        solution_name: ${{ inputs.solution_source_folder}}/${{ inputs.solution_name }}
